编辑原文
theme-kaze/hexo-theme-kaze pull request #78
Opened 2022-12-01 11:16 UTC by shuangxunian

2022-12-02 20:55 UTC, songhn233 requested changes

2022-12-02 20:55 UTC, songhn233 commented on _config.yml
> +editedArticle:
```suggestion
# 编辑原文链接，支持 GitHub、GitLab 等代码仓库
# 需要注意对应链接分支应该为 deploy 产物而不是完整站点
# 详见 https://github.com/theme-kaze/hexo-theme-kaze/issues/77
#------------------------
# EXAMPLE
# enable: true
# repo: https://github.com/theme-kaze/theme-kaze-demo/edit/server/source/
# text: 编辑原文
#------------------------
# 在 front matter 中可以通过同名 editedArticle: false / true 关闭或开启
#------------------------
editLink:
```

2022-12-02 20:55 UTC, songhn233 commented on _config.yml
> +editedArticle:
这个其实可以参照 https://vitepress.vuejs.org/guide/theme-edit-link 插件的设计

通过 `:path` 会更灵活一些，这样后面可能还能拼接其他内容，不过直接追加到最后其实基本也满足了

另外的 text 配置还是需要的，如果为空的话则显示默认的“编辑原文”

---

还有一点就是应该支持在 front matter 中配置开关（`page.editLink`），这样会更加灵活一些
```markdown
---
title: Edit Link
editLink: true
---
Edit-link main page content.
```
我在注释里加上了这两点，麻烦在实际代码处修改下逻辑哈

2022-12-05 07:51 UTC, shuangxunian commented on _config.yml
> +editedArticle:
大佬您好 我对于您说的` 需要注意对应链接分支应该为 deploy 产物而不是完整站点` 这句话不是很理解，因为我之前没参与过提交pr，是我在我的仓库新建一个dev的分支然后将dev的分支关联到你仓库里的devel分支吗？

2022-12-05 08:47 UTC, songhn233 commented on _config.yml
> +editedArticle:
> 大佬您好 我对于您说的` 需要注意对应链接分支应该为 deploy 产物而不是完整站点` 这句话不是很理解，因为我之前没参与过提交pr，是我在我的仓库新建一个dev的分支然后将dev的分支关联到你仓库里的devel分支吗？

没有哈哈，这些注释都是用户说明的一部分。`需要注意对应链接分支应该为 deploy 产物而不是完整站点` 有点歧义。

因为有些用户可能会用 github-pages 方案，把 hexo build & hexo deploy 的静态资源作为一个分支。但是如果实现编辑的话需要跳转到对应的源码分支。

这句话感觉没有必要，正常来说就是会指向源码的分支，我把这句话去掉吧。

2022-12-05 09:00 UTC, shuangxunian commented on _config.yml
> +editedArticle:
好的 明白了 那请问关于` front matter`这个，我的疑问是这个是哪个路径下的，我应该按照什么格式去写呢，我现在的解决方法就是用这里的`editedArticle`下的`enable`去做是否使用这个功能的判断

2022-12-05 09:28 UTC, songhn233 commented on _config.yml
> +editedArticle:
> 好的 明白了 那请问关于` front matter`这个，我的疑问是这个是哪个路径下的，我应该按照什么格式去写呢，我现在的解决方法就是用这里的`editedArticle`下的`enable`去做是否使用这个功能的判断

嗯，可以看到这里 https://github.com/theme-kaze/hexo-theme-kaze/blob/b41d681d72f7396c535f68234b64a35acacf297b/layout/post.ejs#L4-L5

通过 `page.$variable` 就能获取到了，本地测试可以在 markdown 文件里加上对应的字段，然后看下实际表现。

也可以参考 [文档说明](https://hexo.io/zh-cn/docs/front-matter)

2022-12-06 05:47 UTC, shuangxunian commented on _config.yml
> +editedArticle:
我理解了！我去改一下！谢谢！

2022-12-06 11:20 UTC, songhn233 requested changes

2022-12-06 11:20 UTC, songhn233 commented on layout/post.ejs
> +  <% if(page.editLink) { %>
```suggestion
  <% if(theme.editLink.enable && (page.editLink !== false)) { %>
```

这样会更合理一点，首先全局配置的 editedLink 的 enable 可以有一个整体的控制，单个文章中也可以通过 font matter 关闭这个行为

2022-12-06 11:20 UTC, songhn233 commented on _config.yml
> +editedArticle:
```suggestion
editLink:
```

2022-12-08 05:40 UTC, songhn233 approved these changes

2022-12-08 05:41 UTC, merged

2022-12-08 05:41 UTC, songhn233 commented
Thanks.

2022-12-08 05:41 UTC, shuangxunian commented
> 

麻烦大佬了 跟大佬学到了很多 也谢谢大佬 hh~